classes:
  - id: 1
    name: seagrass
    color: [125, 222, 125]
    roles: []
    group_intermediate: seagrass
    group_coarse: seagrass
  - id: 2
    name: trash
    color: [255, 0, 134]
    roles: []
    group_intermediate: trash
    group_coarse: trash
  - id: 3
    name: other coral dead
    color: [114, 60, 61]
    roles: []
    group_intermediate: coral dead
    group_coarse: coral dead
  - id: 4
    name: other coral bleached
    color: [250, 224, 225]
    roles: []
    group_intermediate: coral bleached
    group_coarse: coral bleached
  - id: 5
    name: sand
    color: [194, 178, 128]
    roles: []
    group_intermediate: sand
    group_coarse: sand
  - id: 6
    name: other coral alive
    color: [224, 118, 119]
    roles: []
    group_intermediate: coral alive
    group_coarse: coral alive
  - id: 7
    name: human
    color: [255, 0, 0]
    roles: [ignore_in_point_cloud, ignore_in_cover]
    group_intermediate: human
    group_coarse: human
  - id: 8
    name: transect tools
    color: [8, 205, 12]
    roles: [transect_tools, ignore_in_point_cloud, ignore_in_cover]
    group_intermediate: transect tools
    group_coarse: transect tools
  - id: 9
    name: fish
    color: [255, 255, 0]
    roles: [ignore_in_point_cloud, ignore_in_cover]
    group_intermediate: fish
    group_coarse: fish
  - id: 10
    name: algae covered substrate
    color: [125, 163, 125]
    roles: []
    group_intermediate: algae covered substrate
    group_coarse: algae covered substrate
  - id: 11
    name: other animal
    color: [0, 255, 255]
    roles: []
    group_intermediate: other animal
    group_coarse: other animal
  - id: 12
    name: unknown hard substrate
    color: [125, 125, 125]
    roles: []
    group_intermediate: hard substrate
    group_coarse: hard substrate
  - id: 13
    name: background
    color: [29, 162, 216]
    roles: [ignore_in_point_cloud, ignore_in_cover, background]
    group_intermediate: background
    group_coarse: background
  - id: 14
    name: dark
    color: [31, 31, 31]
    roles: [ignore_in_cover]
    group_intermediate: dark
    group_coarse: dark
  - id: 15
    name: transect line
    color: [0, 255, 0]
    roles: [transect_line, ignore_in_cover]
    group_intermediate: transect line
    group_coarse: transect line
  - id: 16
    name: massive/meandering bleached
    color: [255, 248, 228]
    roles: []
    group_intermediate: massive/meandering bleached
    group_coarse: coral bleached
  - id: 17
    name: massive/meandering alive
    color: [236, 150, 21]
    roles: []
    group_intermediate: massive/meandering alive
    group_coarse: coral alive
  - id: 18
    name: rubble
    color: [161, 153, 128]
    roles: []
    group_intermediate: rubble
    group_coarse: hard substrate
  - id: 19
    name: branching bleached
    color: [252, 231, 240]
    roles: []
    group_intermediate: branching bleached
    group_coarse: coral bleached
  - id: 20
    name: branching dead
    color: [123, 50, 86]
    roles: []
    group_intermediate: branching dead
    group_coarse: coral dead
  - id: 21
    name: millepora
    color: [244, 150, 115]
    roles: []
    group_intermediate: millepora
    group_coarse: coral alive
  - id: 22
    name: branching alive
    color: [226, 91, 157]
    roles: []
    group_intermediate: branching alive
    group_coarse: coral alive
  - id: 23
    name: massive/meandering dead
    color: [134, 86, 18]
    roles: []
    group_intermediate: massive/meandering dead
    group_coarse: coral dead
  - id: 24
    name: clam
    color: [189, 255, 234]
    roles: []
    group_intermediate: clam
    group_coarse: other animal
  - id: 25
    name: acropora alive
    color: [236, 128, 255]
    roles: []
    group_intermediate: coral alive
    group_coarse: coral alive
  - id: 26
    name: sea cucumber
    color: [0, 231, 255]
    roles: []
    group_intermediate: other animal
    group_coarse: other animal
  - id: 27
    name: turbinaria
    color: [228, 255, 119]
    roles: []
    group_intermediate: coral alive
    group_coarse: coral alive
  - id: 28
    name: table acropora alive
    color: [189, 119, 255]
    roles: []
    group_intermediate: coral alive
    group_coarse: coral alive
  - id: 29
    name: sponge
    color: [240, 80, 80]
    roles: []
    group_intermediate: other animal
    group_coarse: other animal
  - id: 30
    name: anemone
    color: [0, 255, 189]
    roles: []
    group_intermediate: other animal
    group_coarse: other animal
  - id: 31
    name: pocillopora alive
    color: [255, 146, 150]
    roles: []
    group_intermediate: coral alive
    group_coarse: coral alive
  - id: 32
    name: table acropora dead
    color: [85, 53, 116]
    roles: []
    group_intermediate: coral dead
    group_coarse: coral dead
  - id: 33
    name: meandering bleached
    color: [251, 243, 216]
    roles: []
    group_intermediate: massive/meandering bleached
    group_coarse: coral bleached
  - id: 34
    name: stylophora alive
    color: [255, 111, 194]
    roles: []
    group_intermediate: coral alive
    group_coarse: coral alive
  - id: 35
    name: sea urchin
    color: [0, 142, 255]
    roles: []
    group_intermediate: other animal
    group_coarse: other animal
  - id: 36
    name: meandering alive
    color: [230, 193, 0]
    roles: []
    group_intermediate: massive/meandering alive
    group_coarse: coral alive
  - id: 37
    name: meandering dead
    color: [119, 100, 14]
    roles: []
    group_intermediate: massive/meandering dead
    group_coarse: coral dead
  - id: 38
    name: crown of thorn
    color: [179, 245, 234]
    roles: []
    group_intermediate: other animal
    group_coarse: other animal
  - id: 39
    name: dead clam
    color: [89, 155, 134]
    roles: []
    group_intermediate: other animal
    group_coarse: other animal
